cart/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail'),
]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate')
]

products/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse
#from django.contrib import admin
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^$', views.product_list, name='product_list'),
]

shop/urls.py
# from django.urls import path
from django.conf.urls import url, include

from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings #new
from django.views.generic import TemplateView

import cart, clients, feedback, orders,products,suppliers
admin.autodiscover()

urlpatterns = [
    # path('admin/', admin.site.urls),

    url(r'^admin', include(admin.site.urls)),
    url(r'^products', include('products.urls', namespace='products')),
    url(r'^feedback', include('feedback.urls', namespace='feedback')),
    url(r'^info', TemplateView.as_view(template_name='info/info.html')),
    url(r'^shares', TemplateView.as_view(template_name='shares/shares.html')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),

    url(r'^', TemplateView.as_view(template_name='index.html')),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 16)]
class CartAddProductForm(forms.Form):
    # quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество")
    quantity = forms.IntegerField(initial=1, label="Количество", min_value=1, max_value=10)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from products.models import *

# Create your views here.

@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')

def CartDetail(request):
    cart = Cart(request)
    prod_photos = Product_photo.objects.filter(product_photo_is_main=True, product_photo_is_active=True)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart/detail.html', locals())

templates/cart/detail.html
{% extends "base.html" %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{% block content %}
<div class="wrapper-products wrapper-products-det">


  <div class="container general-container">

  <h1>Ваша корзина товаров</h1>
  <div style="overflow-x:auto;">
  <table class="table table-responsive">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              {% for item in prod_photos %}
                {% if item.product == product %}
                <a href="{{ product.get_absolute_url }}">
                  <img src="{{item.product_photo.url}}" class="img-responsive" style="max-width: 300px;">
                </a>
                {% endif %}
              {% endfor %}
            </td>
            <td>
              <a href="{{ product.get_absolute_url }}">{{ product.product_name }}</a>
            </td>

            <!-- <td>{{ item.quantity }}</td> -->

            <td>
              <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
                <input type="submit" value="Обновить">
              </form>
            </td>

            <td><a href="{% url "cart:CartRemove" product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} ГРН </td>
            <td class="num">{{ item.total_price }} ГРН </td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td><h3>Всего:</h3></td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} ГРН </td>
        </tr>
    </tbody>
  </table>
  </div>
  <p class="text-right">
    <a href="{% url "products:product_list" %}" class="btn btn-success">Продолжить просмотр</a>
    <a href="{% url "orders:OrderCreate" %}" class="btn btn-info">Оформить заказ</a>
  </p>
</div>
</div>
{% endblock %}