cart/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail'),
]

feedback/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.feedback, name='feedback'),
]

products/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse
#from django.contrib import admin
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^$', views.product_list, name='product_list'),
]

shop/urls.py
# from django.urls import path
from django.conf.urls import url, include

from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings #new
from django.views.generic import TemplateView

import cart, clients, feedback, orders,products,suppliers
admin.autodiscover()

urlpatterns = [
    # path('admin/', admin.site.urls),

    url(r'^admin', include(admin.site.urls)),
    url(r'^products', include('products.urls', namespace='products')),
    url(r'^feedback', include('feedback.urls', namespace='feedback')),
    url(r'^info', TemplateView.as_view(template_name='info/info.html')),
    url(r'^shares', TemplateView.as_view(template_name='shares/shares.html')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),

    url(r'^', TemplateView.as_view(template_name='index.html')),
]

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    {#<!-- <title> {% block title %}{% endblock %} &ndash; My Shop </title>  --> #}
    <title> {% block title %}{% endblock %} </title>

    <!-- Bootstrap core CSS -->
    {# <link href="https://bootswatch.com/4/darkly/bootstrap.css" rel="stylesheet">#}
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400|Lobster|Noto+Serif:400,400i|Old+Standard+TT:400,400i|Philosopher:400,400i&amp;subset=cyrillic,cyrillic-ext" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!--script src="{% static 'js/script.js' %}"></script-->
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../assets/js/ie-emulation-modes-warning.js"></script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

    <!-- for FF, Chrome, Opera -->
    <link rel="icon" type="image/png" href={% static 'base/01.png' %} sizes="16x16">
    <!-- <link rel="icon" type="image/png" href={% static 'base/01.png' %} sizes="32x32"> -->

    <!-- for IE -->
    <link rel="icon" type="image/x-icon" href="{% static 'base/01.png' %}" >
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'base/01.png' %}"/>



    {% block header%}

    {% endblock %}


  </head>

  <body>

    <nav class="navbar navbar-fixed-top navbar-custom" role="navigation" id="nav">
     <div class="container-fluid">
       <div class="navbar-header" >
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
           <img style="max-height: 40px; margin-top: 5px; margin-left: 7px; display:inline;" class="img-responsive"
            src="{% static 'base/01.png' %}" class="img-responsive" title="LOGO">&emsp;

         {# <a class="navbar-brand" href="{% url 'home' %}">Shop name</a>#}
       </div>

       <div id="navbar" class="navbar-collapse collapse navbar-center">
         <ul class="nav navbar-nav">
           <li><a href="/">Главная</a></li>
           <li><a href="{% url 'products:product_list' %}">Все десерты</a></li>
           <li><a href="/shares">Акции</a></li>
           <li><a href="/info">Информация</a></li>
           <li><a href="{% url 'feedback:feedback' %}">Обратная связь</a></li>
           {#<li><a href="{% url 'info:info' %}#section1">Сертификаты</a></li>#}
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a  href="{% url "cart:CartDetail" %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-shopping-cart"> Ваша корзина{% if cart|length > 0 %}({{cart|length}}){% endif %}</span><span class="caret"></span>
               <div id="card">
                 </a>

                 <ul class="dropdown-menu" style="width: auto; padding: 5px;">

                   {% if cart %}
                   <li><a href="{% url "cart:CartDetail" %}">Перейти к корзине</a></li>


                     {% for item in cart %}

                         <li style="white-space: nowrap;">
                            {{item.product.product_name}} - {{item.quantity}} ед.
                           {# <td>{{item.product.product_name}} - {{item.quantity}} ед.</td>#}
                         </li>
                       {% endfor %}
                     {% else %}
                       <td>Корзина пуста</td>
                     {% endif %}




                 </ul>



           </ul>


          <!-- {% if user.is_authenticated %}
             <li class="navbar-text">Вы зашли как: {{ user.get_username }}</li>
             <li><a href="#" class="navbar-link">Выход</a></li>
             {% if user.get_username == 'admin' %}
               <li><a href="#" class="navbar-link">Админка</a></li>
             {% endif %}
             {% else %}
               <li><a href="#" class="navbar-link">Вход</a></li>
               {# <li><a href="{% url 'signup'%}" class="navbar-link">Регистрация</a></li>#}
           {% endif %}  -->

       </div>

     </div>
     <hr>
    </nav>


    <div class="wrapper" id="wrapper">
      <div class="container">




      {% block content %}


      {% endblock %}

      <br>


     <!-- <a href="javascript:" id="return-to-top"><i class="icon-chevron-up"></i></a> -->


     </div>
   </div>

   <div class="container-fluid">
     <footer class="footer fixed-bottom">
       <div class="row">

<img src="http://x-lines.ru/letters/i/cyrillicscript/1196/ffffff/34/0/4ncpbxqtouem7wcy4n6pbcgto5emtwcxrdemhennpt4sko5bpp11yw3yjyor6eno.png" border="0" />

<img src="http://x-lines.ru/letters/i/cyrillicscript/1196/ffffff/22/0/rbbga7mfeposs3jykcoroenxrbenymjy4n6pbpqto8eafwf6foopbc6osuemkegoz5eadwcn4napbcsozdemzwfardemregoz9eabwf64grpbq6oz5emaegoz5emdwcm4n4pbpqozzem5wf64n4o.png" border="0" />
<img src="http://x-lines.ru/letters/i/cyrillicscript/1196/ffffff/22/0/4n97dygoszemjwcb4gbpbcgosmemzwfi4n67bqgoswopbcsto8emmwfh4nhnbwf54g8pbcqozdem3wf64n37bxty4n97bqgtodem7wfs4n67bxsosxemhegozyopdysoz5eabwcn4nay.png" border="0" />
<img src="http://x-lines.ru/letters/i/cyrillicbasic/0001/ffffff/22/0/4nppbxsozzeafwfo4n7pdysttc7nyk3u8yanyptsgeodyc3ygh51aego1deamwfh4napdysoz5emfwf64nh1ycjury.png" border="0" />
<img src="http://x-lines.ru/letters/i/cyrillicscript/1196/ffffff/16/0/4no7bcgoz8earegto8em7wfz4n4pbcgozxemoqty4nppbxsto8ea3wf44n9nbwrofasnbwra4n77ddgozdem5wfordejymtcrdejfwfo4n77ddgozmemhegoweznaegow9emtwfs4n47bcsto8emiwfo4g81bwr7fa.png" border="0" />


       </div>
     </footer>

   </div>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>


{% block title %}
  Главная
{% endblock %}

{% block content %}
<h1>Новинки</h1>


<div id="myCarousel" class="carousel slide" data-interval="1500" data-ride="carousel" data-type="multi" >
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
      <li data-target="#myCarousel" data-slide-to="5"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <center><img src="{% static 'index/okean.JPG' %}" alt="pic" class="img-responsive carousel-img"></center>
      </div>


      <div class="item">
        <center><img src="{% static 'index/klubnika.JPG' %}" alt="pic" class="img-responsive carousel-img"></center>
      </div>

      <div class="item">
        <center><img src="{% static 'index/kosmos.JPG' %}" alt="pic" class="img-responsive carousel-img"></center>
      </div>


	   <div class="item">
        <center><img src="{% static 'index/vanil.JPG' %}" alt="pic" class="img-responsive carousel-img"></center>

      </div>

	   <div class="item">
        <center><img src="{% static 'index/sky.JPG' %}" alt="pic" class="img-responsive carousel-img"></center>

      </div>
      <!-- Left and right controls -->
      <a class="left carousel-control nopadding" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <!--<span class="sr-only">Previous</span> -->
      </a>

      <a class="right carousel-control nopadding" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <!--<span class="sr-only">Next</span> -->
      </a>

    </div>
  </div>
{% endblock %}